# Generated by Django 3.2.5 on 2022-06-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre:'),
        ),
    ]
