# Generated by Django 3.2.5 on 2022-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0004_proovedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion:')),
                ('Telefono', models.CharField(max_length=100, verbose_name='Telefono:')),
            ],
        ),
    ]
