# Generated by Django 3.2.5 on 2022-06-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0005_sucursales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('Serie', models.CharField(max_length=100, verbose_name='Serie:')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen:')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion:')),
            ],
        ),
    ]
