# Generated by Django 3.2.5 on 2022-06-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0006_consola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='descripcion',
            new_name='Descripcion',
        ),
    ]
