# Generated by Django 3.2.5 on 2022-06-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0007_rename_descripcion_consola_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='imagen',
            new_name='Imagen',
        ),
    ]
