# Generated by Django 3.2.5 on 2022-06-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0008_rename_imagen_consola_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('Fecha', models.DateField(verbose_name='Fecha:')),
                ('Descripcion', models.TextField(null=True, verbose_name='Descripcion:')),
                ('Descuento', models.CharField(max_length=100, verbose_name='Descuento:')),
            ],
        ),
    ]
