# Generated by Django 3.2.5 on 2022-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0009_promociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('Observaciones', models.TextField(null=True, verbose_name='Observaciones:')),
            ],
        ),
    ]
