# Generated by Django 3.2.5 on 2022-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Changarro', '0010_merma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(null=True, verbose_name='Descripcion:')),
                ('Fecha', models.DateField(verbose_name='Fecha:')),
                ('Estatus', models.CharField(max_length=100, verbose_name='Estatus:')),
            ],
        ),
    ]
